/* Lunar months and solar terms for the v14.0 clock face.
 *
 * GENERATED by tools/gen_v14_tables.py - do not edit by hand.
 * Regenerate with:
 *     python tools/gen_v14_tables.py <path-to-unifont.hex>
 */

/* The face advertises CAL_YEAR_FIRST..CAL_YEAR_LAST.  Outside that range the
 * third row stays blank rather than showing a wrong date - see cal_row3() in
 * src/calendar.c, which is where the two encodings below are decoded.
 */
#define CAL_YEAR_FIRST 2026
#define CAL_YEAR_LAST  2050
#define CAL_YEARS      25

/* The term table is one year longer than the advertised range, so that a date
 * in the last days of CAL_YEAR_LAST can still see its next term in January.
 * This is the bound term_on() gates on; CAL_YEAR_LAST is the one cal_row3()
 * gates on.
 */
#define CAL_TERM_YEAR_FIRST 2026
#define CAL_TERM_YEAR_LAST  2051
#define CAL_TERM_YEARS      26

/* The lunar rows start earlier than CAL_YEAR_FIRST on purpose: 2026-01-01 is
 * still 2025-11-13 in the lunar year, so a January date needs the previous
 * year's row.  CAL_LUNAR_EPOCH_* is the Gregorian date of LUNAR_YEAR_FIRST's
 * 正月初一, i.e. day 0 of the table.
 */
#define CAL_LUNAR_YEAR_FIRST 2024
#define CAL_LUNAR_YEARS      28
#define CAL_LUNAR_EPOCH_Y    2024
#define CAL_LUNAR_EPOCH_M    2
#define CAL_LUNAR_EPOCH_D    10

/* Packed like the published lunarInfo table:
 *     bits 15..4  length of lunar months 1..12, MSB = month 1, 1 = 30 days
 *     bits  3..0  leap month number, 0 = no leap month
 *     bit  16     leap month length, 1 = 30 days
 */
static const unsigned int CAL_LUNAR_INFO[CAL_LUNAR_YEARS] = {
    0x04b60, 0x0a6e6, 0x0a4e0, 0x0d260, 0x0ea65,  /* 2024-2028 */
    0x0d530, 0x05aa0, 0x076a3, 0x096d0, 0x04afb,  /* 2029-2033 */
    0x04ad0, 0x0a4d0, 0x1d0b6, 0x0d250, 0x0d520,  /* 2034-2038 */
    0x0dd45, 0x0b5a0, 0x056d0, 0x055b2, 0x049b0,  /* 2039-2043 */
    0x0a577, 0x0a4b0, 0x0aa50, 0x1b255, 0x06d20,  /* 2044-2048 */
    0x0ada0, 0x14b63, 0x09370,  /* 2049-2051 */
};

/* Day of the month of each solar term.  Term n sits at (285 + 15n) mod 360
 * degrees of apparent solar longitude, and for every year in this range it
 * falls in the same Gregorian month - tools/gen_v14_tables.py asserts that,
 * which is why only the day has to be stored.  Order within a year is the
 * order of CAL_TERM_MONTH: 小寒, 大寒, 立春, ... 冬至.  One row per year from
 * CAL_TERM_YEAR_FIRST to CAL_TERM_YEAR_LAST inclusive.
 */
static const unsigned char CAL_TERM_MONTH[24] = {
    1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12};
static const unsigned char CAL_TERM_DAY[CAL_TERM_YEARS][24] = {
     5, 20,  4, 18,  5, 20,  5, 20,  5, 21,  5, 21,  7, 23,  7, 23,  7, 23,  8, 23,  7, 22,  7, 22,  /* 2026 */
     5, 20,  4, 19,  6, 21,  5, 20,  6, 21,  6, 21,  7, 23,  8, 23,  8, 23,  8, 23,  7, 22,  7, 22,  /* 2027 */
     6, 20,  4, 19,  5, 20,  4, 19,  5, 20,  5, 21,  6, 22,  7, 22,  7, 22,  8, 23,  7, 22,  6, 21,  /* 2028 */
     5, 20,  3, 18,  5, 20,  4, 20,  5, 21,  5, 21,  7, 22,  7, 23,  7, 23,  8, 23,  7, 22,  7, 21,  /* 2029 */
     5, 20,  4, 18,  5, 20,  5, 20,  5, 21,  5, 21,  7, 23,  7, 23,  7, 23,  8, 23,  7, 22,  7, 22,  /* 2030 */
     5, 20,  4, 19,  6, 21,  5, 20,  6, 21,  6, 21,  7, 23,  8, 23,  8, 23,  8, 23,  7, 22,  7, 22,  /* 2031 */
     6, 20,  4, 19,  5, 20,  4, 19,  5, 20,  5, 21,  6, 22,  7, 22,  7, 22,  8, 23,  7, 22,  6, 21,  /* 2032 */
     5, 20,  3, 18,  5, 20,  4, 20,  5, 21,  5, 21,  7, 22,  7, 23,  7, 23,  8, 23,  7, 22,  7, 21,  /* 2033 */
     5, 20,  4, 18,  5, 20,  5, 20,  5, 21,  5, 21,  7, 23,  7, 23,  7, 23,  8, 23,  7, 22,  7, 22,  /* 2034 */
     5, 20,  4, 19,  6, 21,  5, 20,  5, 21,  6, 21,  7, 23,  7, 23,  8, 23,  8, 23,  7, 22,  7, 22,  /* 2035 */
     6, 20,  4, 19,  5, 20,  4, 19,  5, 20,  5, 21,  6, 22,  7, 22,  7, 22,  8, 23,  7, 22,  6, 21,  /* 2036 */
     5, 20,  3, 18,  5, 20,  4, 20,  5, 21,  5, 21,  7, 22,  7, 23,  7, 23,  8, 23,  7, 22,  7, 21,  /* 2037 */
     5, 20,  4, 18,  5, 20,  5, 20,  5, 21,  5, 21,  7, 23,  7, 23,  7, 23,  8, 23,  7, 22,  7, 22,  /* 2038 */
     5, 20,  4, 19,  6, 21,  5, 20,  5, 21,  6, 21,  7, 23,  7, 23,  8, 23,  8, 23,  7, 22,  7, 22,  /* 2039 */
     6, 20,  4, 19,  5, 20,  4, 19,  5, 20,  5, 21,  6, 22,  7, 22,  7, 22,  8, 23,  7, 22,  6, 21,  /* 2040 */
     5, 20,  3, 18,  5, 20,  4, 20,  5, 20,  5, 21,  7, 22,  7, 23,  7, 22,  8, 23,  7, 22,  7, 21,  /* 2041 */
     5, 20,  4, 18,  5, 20,  4, 20,  5, 21,  5, 21,  7, 23,  7, 23,  7, 23,  8, 23,  7, 22,  7, 22,  /* 2042 */
     5, 20,  4, 19,  6, 21,  5, 20,  5, 21,  6, 21,  7, 23,  7, 23,  8, 23,  8, 23,  7, 22,  7, 22,  /* 2043 */
     6, 20,  4, 19,  5, 20,  4, 19,  5, 20,  5, 21,  6, 22,  7, 22,  7, 22,  7, 23,  7, 22,  6, 21,  /* 2044 */
     5, 20,  3, 18,  5, 20,  4, 19,  5, 20,  5, 21,  6, 22,  7, 23,  7, 22,  8, 23,  7, 22,  7, 21,  /* 2045 */
     5, 20,  4, 18,  5, 20,  4, 20,  5, 21,  5, 21,  7, 22,  7, 23,  7, 23,  8, 23,  7, 22,  7, 22,  /* 2046 */
     5, 20,  4, 19,  5, 21,  5, 20,  5, 21,  6, 21,  7, 23,  7, 23,  8, 23,  8, 23,  7, 22,  7, 22,  /* 2047 */
     6, 20,  4, 19,  5, 20,  4, 19,  5, 20,  5, 20,  6, 22,  7, 22,  7, 22,  7, 23,  7, 21,  6, 21,  /* 2048 */
     5, 19,  3, 18,  5, 20,  4, 19,  5, 20,  5, 21,  6, 22,  7, 22,  7, 22,  8, 23,  7, 22,  7, 21,  /* 2049 */
     5, 20,  3, 18,  5, 20,  4, 20,  5, 21,  5, 21,  7, 22,  7, 23,  7, 23,  8, 23,  7, 22,  7, 22,  /* 2050 */
     5, 20,  4, 19,  5, 21,  5, 20,  5, 21,  6, 21,  7, 23,  7, 23,  7, 23,  8, 23,  7, 22,  7, 22,  /* 2051 */
};
