/* Character codepoints used by the v14.0 clock face.
 *
 * GENERATED by tools/gen_v14_tables.py - do not edit by hand.
 * Regenerate with:
 *     python tools/gen_v14_tables.py <path-to-unifont.hex>
 */


#define UF_C_YEAR    0x5e74
#define UF_C_MONTH   0x6708
#define UF_C_DAY     0x65e5
#define UF_C_WEEK    0x5468
#define UF_C_DEGC    0x2103
#define UF_C_LEAP    0x95f0
#define UF_C_TIAN    0x5929
#define UF_C_HOU     0x540e
#define UF_C_JIN     0x4eca
#define UF_C_CHU     0x521d
#define UF_C_NIAN    0x5eff
#define UF_C_SHI     0x5341

/* 0 = 周日 ... 6 = 周六, matching tm_wday */
static const unsigned short UF_WEEKDAY[7] = {
    0x65e5, 0x4e00, 0x4e8c, 0x4e09, 0x56db, 0x4e94, 0x516d};

/* 0 is unused - a lunar day never prints a bare zero - and is
   emitted as 0 rather than a codepoint, so the table cannot
   reference a glyph the font does not carry. */
static const unsigned short UF_NUMERAL[10] = {
    0, 0x4e00, 0x4e8c, 0x4e09, 0x56db, 0x4e94, 0x516d, 0x4e03, 0x516b, 0x4e5d};

/* index 1..12; index 0 is unused because lunar months are 1-based */
static const unsigned short UF_LUNAR_MONTH[13] = {
    0, 0x6b63, 0x4e8c, 0x4e09, 0x56db, 0x4e94, 0x516d, 0x4e03, 0x516b, 0x4e5d, 0x5341, 0x51ac, 0x814a};

/* the 24 solar terms, in CAL_TERM_DAY order */
static const unsigned short UF_TERM[24][2] = {
    { 0x5c0f, 0x5bd2 },   /* 小寒 */
    { 0x5927, 0x5bd2 },   /* 大寒 */
    { 0x7acb, 0x6625 },   /* 立春 */
    { 0x96e8, 0x6c34 },   /* 雨水 */
    { 0x60ca, 0x86f0 },   /* 惊蛰 */
    { 0x6625, 0x5206 },   /* 春分 */
    { 0x6e05, 0x660e },   /* 清明 */
    { 0x8c37, 0x96e8 },   /* 谷雨 */
    { 0x7acb, 0x590f },   /* 立夏 */
    { 0x5c0f, 0x6ee1 },   /* 小满 */
    { 0x8292, 0x79cd },   /* 芒种 */
    { 0x590f, 0x81f3 },   /* 夏至 */
    { 0x5c0f, 0x6691 },   /* 小暑 */
    { 0x5927, 0x6691 },   /* 大暑 */
    { 0x7acb, 0x79cb },   /* 立秋 */
    { 0x5904, 0x6691 },   /* 处暑 */
    { 0x767d, 0x9732 },   /* 白露 */
    { 0x79cb, 0x5206 },   /* 秋分 */
    { 0x5bd2, 0x9732 },   /* 寒露 */
    { 0x971c, 0x964d },   /* 霜降 */
    { 0x7acb, 0x51ac },   /* 立冬 */
    { 0x5c0f, 0x96ea },   /* 小雪 */
    { 0x5927, 0x96ea },   /* 大雪 */
    { 0x51ac, 0x81f3 },   /* 冬至 */
};